[plugin]
id = "adi.lang.ruby"
name = "Ruby Language Support"
version = "0.1.0"
api_version = 2

[language]
id = "ruby"
extensions = ["rb", "rake", "gemspec"]

[provides]
services = ["adi.indexer.lang.ruby"]
